# Mathcer for ddc.vim

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

# Sorter for ddc.vim

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

# Sources for ddc.vim

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = 'ddc.vim'
depends = ['vim-lsp']

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
on_event = 'InsertEnter'
hook_source = '''
  call ddc#custom#patch_global('sources', ['vim-lsp', 'around', 'file'])

  call ddc#custom#patch_global('sourceOptions', {
    \ '_': {
    \   'matchers': ['matcher_head'],
    \   'sorters': ['sorter_rank'],
    \ },
    \ 'around': {'mark': 'A'},
    \ 'file': {
    \   'mark': 'F',
    \   'isVolatile': v:true,
    \   'forceCompletionPattern': '\S/\S*',
    \ },
    \ 'vim-lsp': {
    \   'mark': 'LSP',
    \   'forceCompletionPattern': '\.\w*|:\w*|->\w*',
    \ })
 
  call ddc#custom#patch_global('sourceParams', {
    \ 'around': {'maxSize': 500},
    \ 'file': {'smartCase': v:true},
    \ })

  " <TAB>: completion.
  inoremap <silent><expr> <TAB>
    \ pumvisible() ? '<C-n>' :
    \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
    \ '<TAB>' : ddc#map#manual_complete()
  
  " <S-TAB>: completion back.
  inoremap <expr><S-TAB> pumvisible() ? "<C-p>" : "<C-h>"

  " 補完ウィンドウでEnter押したときに改行を挿入しない
  inoremap <expr><CR> pumvisible() ? "<C-y>" : "<CR>"

  " 補完ウィンドウでC-j/kで候補を移動する
  " inoremap <expr><C-j> pumvisible() ? "<Down>" : "<C-j>"
  " inoremap <expr><C-k> pumvisible() ? "<Up>" : "<C-k>"
 
  call ddc#enable()
'''

[[plugins]]
repo = 'higashi000/dps-kakkonan'
depends = ['denops.vim']
on_event = 'InsertEnter'

