[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'djangohtml']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i  = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_source = '''
  imap <C-b> <Plug>(neosnippet_expand_or_jump)
  smap <C-b> <Plug>(neosnippet_expand_or_jump)
  xmap <C-b> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=0 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_smart_case=1
    inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
depends = ['deoplete.nvim']
hook_source = '''
    let g:vimtex_compiler_latexmk = {
      \ 'background': 1,
      \ 'build_dir': '',
      \ 'continuous': 1,
      \ 'options': [
      \    '-pdfdvi',
      \    '-verbose',
      \    '-file-line-error',
      \    '-synctex=1',
      \    '-interaction=nonstopmode',
      \],
    \}
    if !exists('g:deoplete#omni#input_patterns')
        let g:deoplete#omni#input_patterns = {}
    endif
    let g:deoplete#omni#input_patterns.tex = g:vimtex#re#deoplete
'''

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', 'djangohtml']

[[plugins]]
repo = 'plytophogy/vim-virtualenv'
on_ft = ['python']

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'lambdalisue/vim-gista'
on_cmd = 'Gista'
hook_source = '''
    let g:gista#client#default_username = 'pddg'
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = '''
    let g:quickrun_config = {
    \ '_' : {
        \ 'runner' : 'vimproc',
        \ 'runner/vimproc/updatetime' : 40,
        \ 'outputter' : 'error',
        \ 'outputter/error/success' : 'buffer',
        \ 'outputter/error/error'   : 'quickfix',
        \ 'outputter/buffer/split' : ':botright 8sp',
    \ },
    \ 'python': {
        \ 'command': 'python3'
    \ }
    \}
    au FileType qf nnoremap <silent><buffer>q :quit<CR>
    let g:quickrun_no_default_key_mappings = 1
    nnoremap <Leader>r :write<CR>:QuickRun -mode n<CR>
    nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
'''
on_ft = ['python']

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['yaml', 'yml']

[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'
on_ft = ['j2']
